"""Print a one-line summary (first docstring sentence + LOC) per module.

Usage: python scripts/module_map.py [package_dir ...]  (default: friday)
Writes docs/architecture/MODULE_MAP.md and prints it.
"""
from __future__ import annotations

import ast
import sys
from pathlib import Path


def summarize(path: Path) -> tuple[str, int]:
    text = path.read_text(encoding="utf-8", errors="replace")
    loc = text.count("\n")
    try:
        doc = ast.get_docstring(ast.parse(text)) or ""
    except SyntaxError:
        doc = "(syntax error)"
    first = doc.strip().split("\n\n")[0].replace("\n", " ").strip()
    return (first[:180] or "(no docstring)"), loc


def main() -> None:
    roots = [Path(a) for a in sys.argv[1:]] or [Path("friday")]
    lines = ["# Module map (generated by scripts/module_map.py)", ""]
    for root in roots:
        for p in sorted(root.rglob("*.py")):
            if "__pycache__" in p.parts or p.name == "__init__.py":
                continue
            s, loc = summarize(p)
            lines.append(f"- `{p.as_posix()}` ({loc}): {s}")
    out = Path("docs/architecture/MODULE_MAP.md")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
